[package]
name = "easyscanlate-ocr"
version.workspace = true
edition.workspace = true

[features]
directml = ["rapidocr-core/directml"]

[dependencies]
easyscanlate-model = { workspace = true }
easyscanlate-settings = { workspace = true }
rapidocr-core = { workspace = true }
image = { workspace = true }
