[package]
name = "easyscanlate-segment"
version.workspace = true
edition.workspace = true

[features]
directml = ["ort/directml"]

[dependencies]
easyscanlate-model = { workspace = true }
easyscanlate-settings = { workspace = true }
image = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true }
