[package]
name = "scanlateit-segment"
version.workspace = true
edition.workspace = true

[features]
directml = ["ort/directml"]

[dependencies]
scanlateit-model = { workspace = true }
scanlateit-settings = { workspace = true }
image = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true }
