[package]
name = "easyscanlate-inpaint"
version.workspace = true
edition.workspace = true

[features]
directml = ["ort/directml"]

[dependencies]
image = { workspace = true }
imageproc = { workspace = true }
inpaint = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true }
easyscanlate-model = { workspace = true }
easyscanlate-settings = { workspace = true }
