name: Build and Release MangaOCRTool

# Workflow Trigger
on:
  workflow_dispatch:

  push:
    branches:
      - minimal-module

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      # 1. Get the code from repository
      - name: Check-out repository
        uses: actions/checkout@v4

      # 2. Set up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install project's dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r minimal_module_requirements.txt

      # 4. Run Nuitka build
      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          mode: standalone
          mingw64: true
          enable-plugins: pyside6
          windows-icon-from-ico: assets/app_icon.ico
          company-name: "YourCompany"
          product-name: "MangaOCRTool"
          file-description: "ManhwaOCR"
          file-version: "0.0.1"
          product-version: "0.0.1"

      # Zip the entire build output
      - name: Zip Full Build Output
        run: |
          cd build/main.dist
          7z a -t7z -mx=9 ..\..\build-output.7z
          cd ..\..
        shell: pwsh

      # Upload the zipped build output as an artifact
      - name: Upload Full Build Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-build-output
          path: build-output.7z